from __future__ import annotations

from html import escape
from pathlib import Path

import pandas as pd

from gridweather.agent.explain import attach_explanations


def build_html_report(prediction_path: Path, output_dir: Path, top_k: int = 30) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(prediction_path, parse_dates=["time"])
    df = attach_explanations(df)
    peak = (
        df.sort_values("pred_risk_score", ascending=False)
        .groupby("tower_id", as_index=False)
        .head(1)
        .sort_values("pred_risk_score", ascending=False)
        .head(top_k)
    )

    rows = []
    for _, row in peak.iterrows():
        cls = "high" if row["pred_risk_level"] >= 2 else "normal"
        rows.append(
            "<tr class='{cls}'><td>{tower}</td><td>{line}</td><td>{time}</td><td>{level}</td>"
            "<td>{score:.1f}</td><td>{dlr:.0f}</td><td>{margin:.1f}%</td><td>{lat:.4f}</td><td>{lon:.4f}</td><td>{why}</td><td>{action}</td></tr>".format(
                cls=cls,
                tower=escape(str(row["tower_id"])),
                line=escape(str(row["line_id"])),
                time=escape(str(row["time"])),
                level=int(row["pred_risk_level"]),
                score=float(row["pred_risk_score"]),
                dlr=float(row.get("dlr_ampacity_a", 0)),
                margin=float(row.get("dlr_margin_pct", 0)),
                lat=float(row["lat"]),
                lon=float(row["lon"]),
                why=escape(str(row["agent_explanation"])),
                action=escape(str(row.get("recommended_action", ""))),
            )
        )

    high_count = int((df["pred_risk_level"] >= 2).sum())
    constrained_count = int((df.get("dlr_margin_pct", pd.Series([999] * len(df))) < 10).sum())
    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>GridWeather-Agent Risk Report</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 32px; color: #1f2937; }}
h1 {{ margin-bottom: 4px; }}
.meta {{ color: #4b5563; margin-bottom: 24px; }}
.summary {{ display: flex; gap: 16px; margin-bottom: 24px; }}
.card {{ border: 1px solid #d1d5db; border-radius: 8px; padding: 14px 18px; min-width: 160px; }}
.num {{ font-size: 28px; font-weight: 700; color: #b91c1c; }}
table {{ border-collapse: collapse; width: 100%; font-size: 14px; }}
th, td {{ border-bottom: 1px solid #e5e7eb; padding: 9px 10px; text-align: left; vertical-align: top; }}
th {{ background: #f3f4f6; }}
tr.high {{ background: #fff7ed; }}
</style>
</head>
<body>
<h1>GridWeather-Agent Risk Report</h1>
<div class="meta">Tower-level icing risk generated by the model and checked by rule-based explanations.</div>
<div class="summary">
<div class="card"><div>Total predictions</div><div class="num">{len(df)}</div></div>
<div class="card"><div>High-risk records</div><div class="num">{high_count}</div></div>
<div class="card"><div>Max score</div><div class="num">{df['pred_risk_score'].max():.1f}</div></div>
<div class="card"><div>Capacity watch</div><div class="num">{constrained_count}</div></div>
</div>
<table>
<thead><tr><th>Tower</th><th>Line</th><th>Time</th><th>Risk level</th><th>Score</th><th>DLR A</th><th>Margin</th><th>Lat</th><th>Lon</th><th>Agent explanation</th><th>Recommended action</th></tr></thead>
<tbody>
{''.join(rows)}
</tbody>
</table>
</body>
</html>"""
    output_path = output_dir / "gridweather_report.html"
    output_path.write_text(html, encoding="utf-8")
    return output_path
